# **LOAD DATA**

In [20]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

from matplotlib import cm
from matplotlib.colors import Normalize


file_path = r"G:\5. PT Raecca Kreasi Indonesia\7. Data Kompetitor\Data Kompetitor SKU Products.xlsx"

df = pd.read_excel(file_path, sheet_name="All Data")

In [21]:
import re

# fungsi cleaning
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)  # hapus simbol
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df["clean_name"] = df["Product Name"].apply(clean_text)

In [22]:
df["tokens"] = df["clean_name"].str.split()

In [23]:
from collections import Counter

brand_keywords = {}

for brand, data in df.groupby("Brand"):
    all_words = []
    for tokens in data["tokens"]:
        all_words.extend(tokens)
    
    word_freq = Counter(all_words).most_common(20)
    brand_keywords[brand] = word_freq

brand_keywords

{'Hanasui': [('hanasui', 34),
  ('lip', 28),
  ('cream', 24),
  ('finish', 21),
  ('tahan', 19),
  ('lama', 19),
  ('tint', 17),
  ('pigmented', 15),
  ('mattedorable', 15),
  ('level', 14),
  ('matte', 14),
  ('velvet', 14),
  ('next', 12),
  ('balm', 12),
  ('liplast', 12),
  ('melembabkan', 11),
  ('ringan', 10),
  ('bdl', 7),
  ('butter', 6),
  ('to', 6)],
 'Implora Cosmetics': [('implora', 48),
  ('lip', 45),
  ('day', 24),
  ('matte', 20),
  ('cream', 16),
  ('lipstick', 15),
  ('to', 12),
  ('for', 12),
  ('bibir', 11),
  ('gloss', 11),
  ('3', 11),
  ('x', 11),
  ('tint', 10),
  ('ombre', 10),
  ('pcs', 10),
  ('velvet', 9),
  ('relaxa', 9),
  ('lite', 6),
  ('lipstik', 6),
  ('satin', 6)],
 "L'Oreal Paris Indonesia": [('l', 26),
  ('oreal', 26),
  ('paris', 26),
  ('matte', 16),
  ('tidak', 16),
  ('resistance', 15),
  ('infallible', 14),
  ('jam', 14),
  ('lipstick', 12),
  ('liquid', 11),
  ('lip', 10),
  ('for', 9),
  ('hingga', 9),
  ('plump', 9),
  ('16', 8),
  ('transferproof', 8),
  ('tahan', 8),
  ('long', 7),
  ('lasting', 7),
  ('hyaluronic', 7)],
 'Maybelline Indonesia': [('maybelline', 39),
  ('superstay', 32),
  ('lipstick', 26),
  ('ink', 25),
  ('matte', 22),
  ('2', 16),
  ('vinyl', 16),
  ('lipstik', 16),
  ('liquid', 14),
  ('lipcream', 12),
  ('jam', 12),
  ('ombre', 12),
  ('teddy', 12),
  ('make', 11),
  ('up', 11),
  ('set', 11),
  ('ml', 11),
  ('tahan', 10),
  ('tint', 10),
  ('free', 10)],
 'Timephoria Id': [('lip', 118),
  ('lipstick', 35),
  ('time', 34),
  ('phoria', 34),
  ('timephoria', 32),
  ('matte', 31),
  ('cream', 26),
  ('stain', 25),
  ('make', 23),
  ('2pcs', 23),
  ('tint', 22),
  ('stellar', 22),
  ('dust', 22),
  ('5ml', 22),
  ('gloss', 22),
  ('hot', 19),
  ('velvet', 19),
  ('4ml', 17),
  ('up', 17),
  ('set', 17)]}

In [24]:
rows = []

for brand, words in brand_keywords.items():
    for word, freq in words:
        rows.append([brand, word, freq])

keyword_df = pd.DataFrame(rows, columns=["Brand", "Keyword", "Frequency"])

keyword_df.sort_values(["Brand", "Frequency"], ascending=[True, False])

                      Brand        Keyword  Frequency
0                   Hanasui        hanasui         34
1                   Hanasui            lip         28
2                   Hanasui          cream         24
3                   Hanasui         finish         21
4                   Hanasui          tahan         19
5                   Hanasui           lama         19
6                   Hanasui           tint         17
7                   Hanasui      pigmented         15
8                   Hanasui   mattedorable         15
9                   Hanasui          level         14
10                  Hanasui          matte         14
11                  Hanasui         velvet         14
12                  Hanasui           next         12
13                  Hanasui           balm         12
14                  Hanasui        liplast         12
15                  Hanasui    melembabkan         11
16                  Hanasui         ringan         10
17                  Hanasui            bdl          7
18                  Hanasui         butter          6
19                  Hanasui             to          6
20        Implora Cosmetics        implora         48
21        Implora Cosmetics            lip         45
22        Implora Cosmetics            day         24
23        Implora Cosmetics          matte         20
24        Implora Cosmetics          cream         16
25        Implora Cosmetics       lipstick         15
26        Implora Cosmetics             to         12
27        Implora Cosmetics            for         12
28        Implora Cosmetics          bibir         11
29        Implora Cosmetics          gloss         11
30        Implora Cosmetics              3         11
31        Implora Cosmetics              x         11
32        Implora Cosmetics           tint         10
33        Implora Cosmetics          ombre         10
34        Implora Cosmetics            pcs         10
35        Implora Cosmetics         velvet          9
36        Implora Cosmetics         relaxa          9
37        Implora Cosmetics           lite          6
38        Implora Cosmetics        lipstik          6
39        Implora Cosmetics          satin          6
40  L'Oreal Paris Indonesia              l         26
41  L'Oreal Paris Indonesia          oreal         26
42  L'Oreal Paris Indonesia          paris         26
43  L'Oreal Paris Indonesia          matte         16
44  L'Oreal Paris Indonesia          tidak         16
45  L'Oreal Paris Indonesia     resistance         15
46  L'Oreal Paris Indonesia     infallible         14
47  L'Oreal Paris Indonesia            jam         14
48  L'Oreal Paris Indonesia       lipstick         12
49  L'Oreal Paris Indonesia         liquid         11
50  L'Oreal Paris Indonesia            lip         10
51  L'Oreal Paris Indonesia            for          9
52  L'Oreal Paris Indonesia         hingga          9
53  L'Oreal Paris Indonesia          plump          9
54  L'Oreal Paris Indonesia             16          8
55  L'Oreal Paris Indonesia  transferproof          8
56  L'Oreal Paris Indonesia          tahan          8
57  L'Oreal Paris Indonesia           long          7
58  L'Oreal Paris Indonesia        lasting          7
59  L'Oreal Paris Indonesia     hyaluronic          7
60     Maybelline Indonesia     maybelline         39
61     Maybelline Indonesia      superstay         32
62     Maybelline Indonesia       lipstick         26
63     Maybelline Indonesia            ink         25
64     Maybelline Indonesia          matte         22
65     Maybelline Indonesia              2         16
66     Maybelline Indonesia          vinyl         16
67     Maybelline Indonesia        lipstik         16
68     Maybelline Indonesia         liquid         14
69     Maybelline Indonesia       lipcream         12
70     Maybelline Indonesia            jam         12
71     Maybelline Indonesia          ombre         12
72     Maybelline Indonesia          teddy         12
73     Maybelline Indonesia           make         11
74     Maybelline Indonesia             up         11
75     Maybelline Indonesia            set         11
76     Maybelline Indonesia             ml         11
77     Maybelline Indonesia          tahan         10
78     Maybelline Indonesia           tint         10
79     Maybelline Indonesia           free         10
80            Timephoria Id            lip        118
81            Timephoria Id       lipstick         35
82            Timephoria Id           time         34
83            Timephoria Id         phoria         34
84            Timephoria Id     timephoria         32
85            Timephoria Id          matte         31
86            Timephoria Id          cream         26
87            Timephoria Id          stain         25
88            Timephoria Id           make         23
89            Timephoria Id           2pcs         23
90            Timephoria Id           tint         22
91            Timephoria Id        stellar         22
92            Timephoria Id           dust         22
93            Timephoria Id            5ml         22
94            Timephoria Id          gloss         22
95            Timephoria Id            hot         19
96            Timephoria Id         velvet         19
97            Timephoria Id            4ml         17
98            Timephoria Id             up         17
99            Timephoria Id            set         17

In [25]:
from itertools import tee

def get_bigrams(tokens):
    a, b = tee(tokens)
    next(b, None)
    return list(zip(a, b))

brand_bigrams = {}

for brand, data in df.groupby("Brand"):
    pairs = []
    for tokens in data["tokens"]:
        pairs.extend(get_bigrams(tokens))
    
    bigram_freq = Counter(pairs).most_common(20)
    brand_bigrams[brand] = bigram_freq

brand_bigrams

{'Hanasui': [(('tahan', 'lama'), 19),
  (('matte', 'finish'), 14),
  (('hanasui', 'mattedorable'), 13),
  (('next', 'level'), 12),
  (('liplast', 'cream'), 12),
  (('lip', 'cream'), 12),
  (('hanasui', 'next'), 10),
  (('mattedorable', 'lip'), 10),
  (('lama', 'pigmented'), 8),
  (('pigmented', 'matte'), 7),
  (('lip', 'tint'), 7),
  (('velvet', 'finish'), 7),
  (('velvet', 'matte'), 7),
  (('butter', 'balm'), 6),
  (('vitamin', 'e'), 6),
  (('fs', 'hanasui'), 6),
  (('level', 'liplast'), 5),
  (('cream', 'liplast'), 5),
  (('cream', 'tahan'), 5),
  (('finish', 'maximum'), 5)],
 'Implora Cosmetics': [(('lip', 'cream'), 16),
  (('day', 'to'), 12),
  (('to', 'day'), 12),
  (('implora', 'lip'), 11),
  (('implora', 'day'), 10),
  (('matte', 'lip'), 9),
  (('lip', 'velvet'), 9),
  (('implora', 'x'), 9),
  (('x', 'relaxa'), 9),
  (('pcs', 'implora'), 8),
  (('relaxa', 'matte'), 8),
  (('lite', 'matte'), 6),
  (('implora', 'jelly'), 6),
  (('jelly', 'tint'), 6),
  (('matte', 'lipcream'), 5),
  (('lip', 'bullet'), 5),
  (('for', '3'), 5),
  (('for', '4'), 5),
  (('day', 'lite'), 4),
  (('lipstick', 'bibir'), 4)],
 "L'Oreal Paris Indonesia": [(('l', 'oreal'), 26),
  (('oreal', 'paris'), 26),
  (('paris', 'infallible'), 14),
  (('matte', 'resistance'), 12),
  (('infallible', 'matte'), 11),
  (('resistance', 'liquid'), 11),
  (('liquid', 'lipstick'), 11),
  (('16', 'jam'), 8),
  (('long', 'lasting'), 7),
  (('hyaluronic', 'acid'), 7),
  (('paris', 'plump'), 7),
  (('plump', 'ambition'), 7),
  (('ambition', 'lip'), 7),
  (('lip', 'oil'), 7),
  (('tahan', 'hingga'), 6),
  (('hingga', '24'), 6),
  (('24', 'jam'), 6),
  (('jam', 'bibir'), 6),
  (('bibir', 'plumpy'), 6),
  (('plumpy', 'lembab'), 6)],
 'Maybelline Indonesia': [(('maybelline', 'superstay'), 26),
  (('vinyl', 'ink'), 15),
  (('superstay', 'vinyl'), 14),
  (('make', 'up'), 11),
  (('superstay', 'matte'), 10),
  (('matte', 'ink'), 10),
  (('ombre', 'set'), 10),
  (('2', 'pcs'), 9),
  (('long', 'lasting'), 8),
  (('liquid', 'lipstik'), 8),
  (('set', 'lipstick'), 7),
  (('shiny', 'pigmented'), 7),
  (('pigmented', 'liquid'), 7),
  (('lipstik', 'lipstick'), 7),
  (('lipstick', 'make'), 7),
  (('superstay', 'teddy'), 7),
  (('teddy', 'tint'), 7),
  (('lipstick', 'lipcream'), 6),
  (('ink', '2'), 6),
  (('pcs', 'ombre'), 6)],
 'Timephoria Id': [(('time', 'phoria'), 34),
  (('lip', 'cream'), 26),
  (('lip', 'stain'), 24),
  (('lip', 'tint'), 22),
  (('stellar', 'dust'), 22),
  (('dust', 'lip'), 22),
  (('stain', '5ml'), 22),
  (('lip', 'gloss'), 22),
  (('make', 'up'), 17),
  (('hot', 'sale'), 15),
  (('lipstick', 'lip'), 14),
  (('lip', 'matte'), 13),
  (('pcs', 'stellar'), 12),
  (('long', 'lasting'), 12),
  (('5ml', 'lipstick'), 11),
  (('gloss', 'lipcream'), 11),
  (('eternal', 'lip'), 10),
  (('2', 'pcs'), 10),
  (('velvet', 'lip'), 10),
  (('tint', 'lip'), 10)]}

In [26]:
rows = []

for brand, pairs in brand_bigrams.items():
    for pair, freq in pairs:
        rows.append([brand, " ".join(pair), freq])

bigram_df = pd.DataFrame(rows, columns=["Brand", "Bigram", "Frequency"])

bigram_df.sort_values(["Brand", "Frequency"], ascending=[True, False])

                      Brand                Bigram  Frequency
0                   Hanasui            tahan lama         19
1                   Hanasui          matte finish         14
2                   Hanasui  hanasui mattedorable         13
3                   Hanasui            next level         12
4                   Hanasui         liplast cream         12
5                   Hanasui             lip cream         12
6                   Hanasui          hanasui next         10
7                   Hanasui      mattedorable lip         10
8                   Hanasui        lama pigmented          8
9                   Hanasui       pigmented matte          7
10                  Hanasui              lip tint          7
11                  Hanasui         velvet finish          7
12                  Hanasui          velvet matte          7
13                  Hanasui           butter balm          6
14                  Hanasui             vitamin e          6
15                  Hanasui            fs hanasui          6
16                  Hanasui         level liplast          5
17                  Hanasui         cream liplast          5
18                  Hanasui           cream tahan          5
19                  Hanasui        finish maximum          5
20        Implora Cosmetics             lip cream         16
21        Implora Cosmetics                day to         12
22        Implora Cosmetics                to day         12
23        Implora Cosmetics           implora lip         11
24        Implora Cosmetics           implora day         10
25        Implora Cosmetics             matte lip          9
26        Implora Cosmetics            lip velvet          9
27        Implora Cosmetics             implora x          9
28        Implora Cosmetics              x relaxa          9
29        Implora Cosmetics           pcs implora          8
30        Implora Cosmetics          relaxa matte          8
31        Implora Cosmetics            lite matte          6
32        Implora Cosmetics         implora jelly          6
33        Implora Cosmetics            jelly tint          6
34        Implora Cosmetics        matte lipcream          5
35        Implora Cosmetics            lip bullet          5
36        Implora Cosmetics                 for 3          5
37        Implora Cosmetics                 for 4          5
38        Implora Cosmetics              day lite          4
39        Implora Cosmetics        lipstick bibir          4
40  L'Oreal Paris Indonesia               l oreal         26
41  L'Oreal Paris Indonesia           oreal paris         26
42  L'Oreal Paris Indonesia      paris infallible         14
43  L'Oreal Paris Indonesia      matte resistance         12
44  L'Oreal Paris Indonesia      infallible matte         11
45  L'Oreal Paris Indonesia     resistance liquid         11
46  L'Oreal Paris Indonesia       liquid lipstick         11
47  L'Oreal Paris Indonesia                16 jam          8
48  L'Oreal Paris Indonesia          long lasting          7
49  L'Oreal Paris Indonesia       hyaluronic acid          7
50  L'Oreal Paris Indonesia           paris plump          7
51  L'Oreal Paris Indonesia        plump ambition          7
52  L'Oreal Paris Indonesia          ambition lip          7
53  L'Oreal Paris Indonesia               lip oil          7
54  L'Oreal Paris Indonesia          tahan hingga          6
55  L'Oreal Paris Indonesia             hingga 24          6
56  L'Oreal Paris Indonesia                24 jam          6
57  L'Oreal Paris Indonesia             jam bibir          6
58  L'Oreal Paris Indonesia          bibir plumpy          6
59  L'Oreal Paris Indonesia         plumpy lembab          6
60     Maybelline Indonesia  maybelline superstay         26
61     Maybelline Indonesia             vinyl ink         15
62     Maybelline Indonesia       superstay vinyl         14
63     Maybelline Indonesia               make up         11
64     Maybelline Indonesia       superstay matte         10
65     Maybelline Indonesia             matte ink         10
66     Maybelline Indonesia             ombre set         10
67     Maybelline Indonesia                 2 pcs          9
68     Maybelline Indonesia          long lasting          8
69     Maybelline Indonesia        liquid lipstik          8
70     Maybelline Indonesia          set lipstick          7
71     Maybelline Indonesia       shiny pigmented          7
72     Maybelline Indonesia      pigmented liquid          7
73     Maybelline Indonesia      lipstik lipstick          7
74     Maybelline Indonesia         lipstick make          7
75     Maybelline Indonesia       superstay teddy          7
76     Maybelline Indonesia            teddy tint          7
77     Maybelline Indonesia     lipstick lipcream          6
78     Maybelline Indonesia                 ink 2          6
79     Maybelline Indonesia             pcs ombre          6
80            Timephoria Id           time phoria         34
81            Timephoria Id             lip cream         26
82            Timephoria Id             lip stain         24
83            Timephoria Id              lip tint         22
84            Timephoria Id          stellar dust         22
85            Timephoria Id              dust lip         22
86            Timephoria Id             stain 5ml         22
87            Timephoria Id             lip gloss         22
88            Timephoria Id               make up         17
89            Timephoria Id              hot sale         15
90            Timephoria Id          lipstick lip         14
91            Timephoria Id             lip matte         13
92            Timephoria Id           pcs stellar         12
93            Timephoria Id          long lasting         12
94            Timephoria Id          5ml lipstick         11
95            Timephoria Id        gloss lipcream         11
96            Timephoria Id           eternal lip         10
97            Timephoria Id                 2 pcs         10
98            Timephoria Id            velvet lip         10
99            Timephoria Id              tint lip         10

In [27]:
df["title_length"] = df["clean_name"].apply(lambda x: len(x.split()))

df.groupby("Brand")["title_length"].mean().sort_values(ascending=False)

Brand
L'Oreal Paris Indonesia    21.500000
Timephoria Id              19.803030
Hanasui                    17.411765
Maybelline Indonesia       15.736842
Implora Cosmetics          10.140000
Name: title_length, dtype: float64

In [28]:
rows = []

for brand, data in df.groupby("Brand"):
    for _, row in data.iterrows():
        for word in row["tokens"]:
            rows.append([brand, word, row["Revenue(Rp)"]])

rev_df = pd.DataFrame(rows, columns=["Brand", "Keyword", "Revenue"])

keyword_revenue = (
    rev_df.groupby(["Brand", "Keyword"])["Revenue"]
    .sum()
    .reset_index()
    .sort_values(["Brand", "Revenue"], ascending=[True, False])
)

keyword_revenue

                       Brand          Keyword       Revenue
14                   Hanasui             balm  1.098420e+10
56                   Hanasui          hanasui  9.217933e+09
70                   Hanasui              lip  7.555470e+09
68                   Hanasui            level  6.921015e+09
92                   Hanasui             next  6.920130e+09
34                   Hanasui            cream  6.703569e+09
115                  Hanasui             tint  6.280186e+09
72                   Hanasui          liplast  6.104234e+09
65                   Hanasui             lama  6.086091e+09
113                  Hanasui            tahan  6.086091e+09
17                   Hanasui            bibir  5.648081e+09
27                   Hanasui           butter  5.492100e+09
44                   Hanasui           finish  4.728810e+09
84                   Hanasui      melembabkan  4.491142e+09
69                   Hanasui      lightweight  3.867571e+09
98                   Hanasui        pigmented  3.604607e+09
81                   Hanasui            matte  3.559360e+09
102                  Hanasui           ringan  3.408041e+09
55                   Hanasui            gloss  3.359579e+09
33                   Hanasui         coverage  3.051674e+09
83                   Hanasui          maximum  3.051674e+09
16                   Hanasui           beauty  2.746492e+09
117                  Hanasui           tinted  2.746492e+09
30                   Hanasui            color  2.745608e+09
32                   Hanasui            cover  2.745608e+09
50                   Hanasui            gelap  2.745608e+09
60                   Hanasui            hyper  2.745608e+09
86                   Hanasui      mencerahkan  2.745608e+09
118                  Hanasui               to  2.243926e+09
66                   Hanasui          lasting  1.870539e+09
123                  Hanasui           velvet  1.676251e+09
82                   Hanasui     mattedorable  1.507347e+09
77                   Hanasui             long  1.256568e+09
20                   Hanasui           blurry  1.122848e+09
122                  Hanasui               up  1.122848e+09
11                   Hanasui                8  1.121963e+09
18                   Hanasui             blur  1.121963e+09
19                   Hanasui         blurring  1.121963e+09
41                   Hanasui           effect  1.121963e+09
62                   Hanasui              jam  1.121963e+09
100                  Hanasui          powdery  1.121963e+09
112                  Hanasui     stainlasting  1.121963e+09
127                  Hanasui           watery  1.121963e+09
47                   Hanasui          formula  1.107490e+09
120                  Hanasui    transferproof  1.107490e+09
13                   Hanasui             anti  9.405710e+08
51                   Hanasui            geser  9.405710e+08
57                   Hanasui          hidrasi  9.405710e+08
74                   Hanasui         lipstick  9.405710e+08
97                   Hanasui          optimal  9.405710e+08
108                  Hanasui      smudgeproof  9.405710e+08
88                   Hanasui     moisturizing  9.306284e+08
121                  Hanasui         twinpack  8.588628e+08
111                  Hanasui            stain  7.815504e+08
73                   Hanasui             lips  6.159874e+08
31                   Hanasui           colour  6.146314e+08
53                   Hanasui           glazed  6.146314e+08
54                   Hanasui     glazedorable  6.146314e+08
59                   Hanasui        hydrating  6.146314e+08
99                   Hanasui           plumpy  6.146314e+08
114                  Hanasui       technology  6.146314e+08
124                  Hanasui          vibrant  6.146314e+08
125                  Hanasui            vinyl  6.146314e+08
37                   Hanasui           double  3.639557e+08
22                   Hanasui             boba  3.197192e+08
39                   Hanasui                e  2.374065e+08
126                  Hanasui          vitamin  2.374065e+08
94                   Hanasui              oil  1.908038e+08
95                   Hanasui            olive  1.908038e+08
116                  Hanasui      tintdorable  1.684282e+08
85                   Hanasui      melembapkan  1.669190e+08
91                   Hanasui          natural  1.669190e+08
35                   Hanasui          creator  1.316093e+08
42                   Hanasui        exclusive  1.316093e+08
40                   Hanasui          edition  5.787395e+07
89                   Hanasui    mouisturizing  4.795867e+07
67                   Hanasui            latte  4.660267e+07
80                   Hanasui           matcha  4.660267e+07
93                   Hanasui              non  4.660267e+07
119                  Hanasui     transferable  4.660267e+07
128                  Hanasui             with  4.660267e+07
104                  Hanasui              sbd  2.559281e+07
15                   Hanasui              bdl  2.227764e+07
43                   Hanasui            fancy  1.899429e+07
71                   Hanasui         lipcream  1.708091e+07
49                   Hanasui               fs  1.446712e+07
96                   Hanasui            ombre  1.236236e+07
110                  Hanasui          special  1.169130e+07
0                    Hanasui               01  9.497146e+06
1                    Hanasui               04  9.497146e+06
2                    Hanasui               07  9.497146e+06
3                    Hanasui               08  9.497146e+06
4                    Hanasui               10  9.497146e+06
5                    Hanasui               11  9.497146e+06
6                    Hanasui               12  9.497146e+06
7                    Hanasui               14  9.497146e+06
8                    Hanasui               15  9.497146e+06
9                    Hanasui               16  9.497146e+06
10                   Hanasui                5  9.497146e+06
12                   Hanasui            amaze  9.497146e+06
25                   Hanasui            brick  9.497146e+06
28                   Hanasui             chic  9.497146e+06
29                   Hanasui           classy  9.497146e+06
38                   Hanasui            dusty  9.497146e+06
45                   Hanasui            flame  9.497146e+06
52                   Hanasui            glame  9.497146e+06
63                   Hanasui             kiss  9.497146e+06
109                  Hanasui           sparks  9.497146e+06
101                  Hanasui            promo  7.549076e+06
105                  Hanasui           series  7.549076e+06
78                   Hanasui      longlasting  2.240606e+06
46                   Hanasui            flash  1.653440e+06
58                   Hanasui              hot  1.653440e+06
103                  Hanasui             sale  1.653440e+06
75                   Hanasui          liptint  1.509225e+06
21                   Hanasui            blush  8.846128e+05
23                   Hanasui           bounce  8.846128e+05
24                   Hanasui           bouncy  8.846128e+05
64                   Hanasui              kit  8.846128e+05
26                   Hanasui         bundling  6.849288e+05
106                  Hanasui            serum  6.849288e+05
107                  Hanasui         sleeping  6.849288e+05
36                   Hanasui              dct  0.000000e+00
48                   Hanasui             free  0.000000e+00
61                   Hanasui             icha  0.000000e+00
76                   Hanasui             live  0.000000e+00
79                   Hanasui             mask  0.000000e+00
87                   Hanasui          mineral  0.000000e+00
90                   Hanasui              mud  0.000000e+00
169        Implora Cosmetics              day  4.797531e+09
190        Implora Cosmetics          implora  4.303441e+09
214        Implora Cosmetics            matte  3.752193e+09
207        Implora Cosmetics         lipstick  3.578361e+09
150        Implora Cosmetics            bibir  3.504077e+09
208        Implora Cosmetics          lipstik  3.398080e+09
182        Implora Cosmetics            gloss  3.343780e+09
234        Implora Cosmetics           ringan  2.463341e+09
245        Implora Cosmetics               to  2.398765e+09
210        Implora Cosmetics             lite  2.316365e+09
144        Implora Cosmetics             acid  2.301688e+09
188        Implora Cosmetics       hyaluronic  2.301688e+09
205        Implora Cosmetics         lipcream  2.301688e+09
216        Implora Cosmetics      melembapkan  2.301688e+09
204        Implora Cosmetics              lip  1.574009e+09
246        Implora Cosmetics    transferproof  1.289514e+09
200        Implora Cosmetics          lasting  9.842113e+08
211        Implora Cosmetics             long  9.827955e+08
191        Implora Cosmetics          intense  8.375258e+08
166        Implora Cosmetics            cream  6.619674e+08
228        Implora Cosmetics        pigmented  4.521087e+08
153        Implora Cosmetics        blurmatte  4.519885e+08
158        Implora Cosmetics            caffe  4.519885e+08
162        Implora Cosmetics        colorlock  4.519885e+08
170        Implora Cosmetics           dengan  4.519885e+08
232        Implora Cosmetics       protection  4.519885e+08
240        Implora Cosmetics           shield  4.519885e+08
249        Implora Cosmetics               uv  4.519885e+08
235        Implora Cosmetics            satin  2.289284e+08
248        Implora Cosmetics            urban  2.007511e+08
250        Implora Cosmetics           velvet  1.622841e+08
164        Implora Cosmetics         cosmetic  1.601131e+08
147        Implora Cosmetics         approved  1.453130e+08
157        Implora Cosmetics               by  1.452697e+08
201        Implora Cosmetics      latuconsina  1.452697e+08
230        Implora Cosmetics           prilly  1.452697e+08
244        Implora Cosmetics             tint  1.406232e+08
134        Implora Cosmetics                3  1.217715e+08
220        Implora Cosmetics            ombre  1.199112e+08
165        Implora Cosmetics           crayon  1.159796e+08
138        Implora Cosmetics                5  1.143646e+08
176        Implora Cosmetics           finish  1.129488e+08
184        Implora Cosmetics               gr  1.129488e+08
209        Implora Cosmetics          liptint  9.031067e+07
192        Implora Cosmetics            jelly  8.189481e+07
173        Implora Cosmetics                e  8.005721e+07
221        Implora Cosmetics            omega  8.005721e+07
252        Implora Cosmetics              vit  8.005721e+07
253        Implora Cosmetics             with  8.005721e+07
154        Implora Cosmetics           bullet  7.576096e+07
179        Implora Cosmetics        gantungan  7.388694e+07
198        Implora Cosmetics            kunci  7.388694e+07
178        Implora Cosmetics             free  7.305340e+07
194        Implora Cosmetics         keychain  7.264584e+07
149        Implora Cosmetics             best  5.548136e+07
163        Implora Cosmetics            combo  5.548136e+07
212        Implora Cosmetics             look  5.548136e+07
236        Implora Cosmetics          selling  5.548136e+07
146        Implora Cosmetics              and  4.993828e+07
159        Implora Cosmetics            cheek  4.993828e+07
160        Implora Cosmetics           cherry  4.858397e+07
168        Implora Cosmetics              dan  4.858397e+07
199        Implora Cosmetics             lama  4.858397e+07
227        Implora Cosmetics           perona  4.858397e+07
229        Implora Cosmetics             pipi  4.858397e+07
242        Implora Cosmetics            tahan  4.858397e+07
238        Implora Cosmetics           series  1.038733e+07
129        Implora Cosmetics               01  1.036641e+07
130        Implora Cosmetics               03  1.036641e+07
224        Implora Cosmetics       passionate  1.036641e+07
247        Implora Cosmetics         uplifted  1.036641e+07
171        Implora Cosmetics             dewy  8.790136e+06
225        Implora Cosmetics              pcs  7.287243e+06
177        Implora Cosmetics              for  7.102755e+06
218        Implora Cosmetics            moist  3.916868e+06
155        Implora Cosmetics         bundling  3.873596e+06
239        Implora Cosmetics            serum  3.873596e+06
137        Implora Cosmetics              49k  2.805353e+06
167        Implora Cosmetics           creamy  2.383506e+06
196        Implora Cosmetics           korean  2.039571e+06
206        Implora Cosmetics             lips  2.039571e+06
254        Implora Cosmetics                x  1.874027e+06
143        Implora Cosmetics              70k  1.415746e+06
139        Implora Cosmetics              50k  1.407092e+06
187        Implora Cosmetics           honest  1.403558e+06
140        Implora Cosmetics              55k  1.354318e+06
132        Implora Cosmetics                2  1.126727e+06
186        Implora Cosmetics        hazelnude  1.043574e+06
223        Implora Cosmetics            paket  6.472576e+05
135        Implora Cosmetics                4  5.420927e+05
161        Implora Cosmetics             cici  4.218475e+05
175        Implora Cosmetics        exclusive  4.218475e+05
180        Implora Cosmetics            gemas  4.218475e+05
131        Implora Cosmetics                1  4.075610e+05
156        Implora Cosmetics              buy  4.075610e+05
181        Implora Cosmetics              get  4.075610e+05
237        Implora Cosmetics         serenity  4.075610e+05
136        Implora Cosmetics              45k  1.202452e+05
152        Implora Cosmetics         blooming  4.327191e+04
172        Implora Cosmetics              duo  4.327191e+04
183        Implora Cosmetics          glowing  4.327191e+04
193        Implora Cosmetics         kerajaan  4.327191e+04
133        Implora Cosmetics             2211  0.000000e+00
141        Implora Cosmetics             60ml  0.000000e+00
142        Implora Cosmetics              65k  0.000000e+00
145        Implora Cosmetics          aliyyah  0.000000e+00
148        Implora Cosmetics           barley  0.000000e+00
151        Implora Cosmetics            black  0.000000e+00
174        Implora Cosmetics         excluive  0.000000e+00
185        Implora Cosmetics            grape  0.000000e+00
189        Implora Cosmetics            iicha  0.000000e+00
195        Implora Cosmetics             kohl  0.000000e+00
197        Implora Cosmetics         kosmetik  0.000000e+00
202        Implora Cosmetics           launch  0.000000e+00
203        Implora Cosmetics            lemon  0.000000e+00
213        Implora Cosmetics           lotion  0.000000e+00
215        Implora Cosmetics            mawar  0.000000e+00
217        Implora Cosmetics            milky  0.000000e+00
219        Implora Cosmetics              new  0.000000e+00
222        Implora Cosmetics          package  0.000000e+00
226        Implora Cosmetics           pencil  0.000000e+00
231        Implora Cosmetics       priscillia  0.000000e+00
233        Implora Cosmetics           relaxa  0.000000e+00
241        Implora Cosmetics         softbrow  0.000000e+00
243        Implora Cosmetics           ticket  0.000000e+00
251        Implora Cosmetics           vilmei  0.000000e+00
289  L'Oreal Paris Indonesia                l  4.856138e+09
311  L'Oreal Paris Indonesia            oreal  4.856138e+09
314  L'Oreal Paris Indonesia            paris  4.856138e+09
318  L'Oreal Paris Indonesia       resistance  4.790325e+09
284  L'Oreal Paris Indonesia       infallible  4.789933e+09
326  L'Oreal Paris Indonesia            tidak  4.573932e+09
287  L'Oreal Paris Indonesia              jam  4.079572e+09
256  L'Oreal Paris Indonesia               16  4.034900e+09
328  L'Oreal Paris Indonesia    transferproof  4.034900e+09
303  L'Oreal Paris Indonesia            matte  3.039857e+09
297  L'Oreal Paris Indonesia         lipstick  3.020055e+09
299  L'Oreal Paris Indonesia           liquid  3.019663e+09
262  L'Oreal Paris Indonesia             acid  2.306580e+09
283  L'Oreal Paris Indonesia       hyaluronic  2.306580e+09
292  L'Oreal Paris Indonesia          lasting  2.284039e+09
301  L'Oreal Paris Indonesia             long  2.284039e+09
276  L'Oreal Paris Indonesia              for  2.267559e+09
273  L'Oreal Paris Indonesia           dengan  2.264630e+09
288  L'Oreal Paris Indonesia           kering  2.264630e+09
327  L'Oreal Paris Indonesia         transfer  2.264630e+09
296  L'Oreal Paris Indonesia              lip  1.816281e+09
282  L'Oreal Paris Indonesia           hingga  1.814942e+09
298  L'Oreal Paris Indonesia          lipstik  1.789679e+09
271  L'Oreal Paris Indonesia            cream  1.770270e+09
280  L'Oreal Paris Indonesia           glossy  1.770270e+09
291  L'Oreal Paris Indonesia            laque  1.770270e+09
302  L'Oreal Paris Indonesia      longlasting  1.770270e+09
308  L'Oreal Paris Indonesia           nyaman  1.770270e+09
315  L'Oreal Paris Indonesia        pigmented  1.770270e+09
265  L'Oreal Paris Indonesia             baru  1.060614e+09
300  L'Oreal Paris Indonesia       livestream  7.539386e+08
324  L'Oreal Paris Indonesia          special  7.519959e+08
316  L'Oreal Paris Indonesia            plump  8.796052e+07
325  L'Oreal Paris Indonesia            tahan  6.408105e+07
267  L'Oreal Paris Indonesia            bibir  4.875109e+07
264  L'Oreal Paris Indonesia         ambition  4.601100e+07
310  L'Oreal Paris Indonesia              oil  4.601100e+07
258  L'Oreal Paris Indonesia               24  4.467194e+07
294  L'Oreal Paris Indonesia           lembab  4.467194e+07
295  L'Oreal Paris Indonesia          lengket  4.467194e+07
317  L'Oreal Paris Indonesia           plumpy  4.467194e+07
285  L'Oreal Paris Indonesia          instant  4.194951e+07
329  L'Oreal Paris Indonesia       tripeptide  4.194951e+07
270  L'Oreal Paris Indonesia            color  1.980152e+07
286  L'Oreal Paris Indonesia          intense  1.980152e+07
319  L'Oreal Paris Indonesia            riche  1.980152e+07
330  L'Oreal Paris Indonesia           volume  1.980152e+07
290  L'Oreal Paris Indonesia             lama  1.940911e+07
266  L'Oreal Paris Indonesia             best  9.502822e+06
309  L'Oreal Paris Indonesia               of  9.502822e+06
313  L'Oreal Paris Indonesia             pack  9.502822e+06
322  L'Oreal Paris Indonesia           seller  5.207540e+06
323  L'Oreal Paris Indonesia           shades  5.207540e+06
259  L'Oreal Paris Indonesia                3  4.295282e+06
257  L'Oreal Paris Indonesia                2  4.079151e+06
279  L'Oreal Paris Indonesia            gloss  4.079151e+06
274  L'Oreal Paris Indonesia        exclusive  2.928506e+06
255  L'Oreal Paris Indonesia              125  2.639224e+06
268  L'Oreal Paris Indonesia        cleansing  2.639224e+06
278  L'Oreal Paris Indonesia          garnier  2.639224e+06
304  L'Oreal Paris Indonesia         micellar  2.639224e+06
305  L'Oreal Paris Indonesia               ml  2.639224e+06
320  L'Oreal Paris Indonesia           sakura  2.639224e+06
331  L'Oreal Paris Indonesia            water  2.639224e+06
269  L'Oreal Paris Indonesia            clear  2.027056e+06
272  L'Oreal Paris Indonesia          crystal  2.027056e+06
260  L'Oreal Paris Indonesia                5  1.128389e+06
275  L'Oreal Paris Indonesia            flush  6.267191e+05
312  L'Oreal Paris Indonesia              out  6.267191e+05
293  L'Oreal Paris Indonesia               le  3.924108e+05
263  L'Oreal Paris Indonesia        affiliate  3.590627e+05
261  L'Oreal Paris Indonesia              611  0.000000e+00
277  L'Oreal Paris Indonesia             free  0.000000e+00
281  L'Oreal Paris Indonesia         hawthorn  0.000000e+00
306  L'Oreal Paris Indonesia            naked  0.000000e+00
307  L'Oreal Paris Indonesia              not  0.000000e+00
321  L'Oreal Paris Indonesia             sale  0.000000e+00

In [29]:
rows = []

for brand, data in df.groupby("Brand"):
    for _, row in data.iterrows():
        for word in row["tokens"]:
            rows.append([brand, word, row["Item Sold"]])

sold_df = pd.DataFrame(rows, columns=["Brand", "Keyword", "ItemSold"])

keyword_sold = (
    sold_df.groupby(["Brand", "Keyword"])["ItemSold"]
    .sum()
    .reset_index()
    .sort_values(["Brand", "ItemSold"], ascending=[True, False])
)

keyword_sold

                       Brand          Keyword  ItemSold
14                   Hanasui             balm    553866
56                   Hanasui          hanasui    423870
70                   Hanasui              lip    374464
68                   Hanasui            level    328652
92                   Hanasui             next    328647
115                  Hanasui             tint    315528
34                   Hanasui            cream    293272
17                   Hanasui            bibir    283857
27                   Hanasui           butter    276933
65                   Hanasui             lama    267224
113                  Hanasui            tahan    267224
72                   Hanasui          liplast    267179
44                   Hanasui           finish    213232
84                   Hanasui      melembabkan    208229
69                   Hanasui      lightweight    195055
55                   Hanasui            gloss    157619
98                   Hanasui        pigmented    156595
81                   Hanasui            matte    153563
102                  Hanasui           ringan    146681
16                   Hanasui           beauty    138469
117                  Hanasui           tinted    138469
30                   Hanasui            color    138464
32                   Hanasui            cover    138464
50                   Hanasui            gelap    138464
60                   Hanasui            hyper    138464
86                   Hanasui      mencerahkan    138464
33                   Hanasui         coverage    133587
83                   Hanasui          maximum    133587
118                  Hanasui               to    113182
123                  Hanasui           velvet     79640
66                   Hanasui          lasting     78051
82                   Hanasui     mattedorable     68465
77                   Hanasui             long     58896
20                   Hanasui           blurry     56596
122                  Hanasui               up     56596
11                   Hanasui                8     56591
18                   Hanasui             blur     56591
19                   Hanasui         blurring     56591
41                   Hanasui           effect     56591
62                   Hanasui              jam     56591
100                  Hanasui          powdery     56591
112                  Hanasui     stainlasting     56591
127                  Hanasui           watery     56591
47                   Hanasui          formula     52060
120                  Hanasui    transferproof     52060
13                   Hanasui             anti     44779
51                   Hanasui            geser     44779
57                   Hanasui          hidrasi     44779
74                   Hanasui         lipstick     44779
97                   Hanasui          optimal     44779
108                  Hanasui      smudgeproof     44779
88                   Hanasui     moisturizing     33285
111                  Hanasui            stain     26449
121                  Hanasui         twinpack     26289
73                   Hanasui             lips     19209
31                   Hanasui           colour     19168
53                   Hanasui           glazed     19168
54                   Hanasui     glazedorable     19168
59                   Hanasui        hydrating     19168
99                   Hanasui           plumpy     19168
114                  Hanasui       technology     19168
124                  Hanasui          vibrant     19168
125                  Hanasui            vinyl     19168
37                   Hanasui           double     17231
22                   Hanasui             boba     14512
39                   Hanasui                e      8927
126                  Hanasui          vitamin      8927
116                  Hanasui      tintdorable      7319
85                   Hanasui      melembapkan      7281
91                   Hanasui          natural      7281
94                   Hanasui              oil      5854
95                   Hanasui            olive      5854
40                   Hanasui          edition      3736
35                   Hanasui          creator      3602
42                   Hanasui        exclusive      3602
89                   Hanasui    mouisturizing      3114
67                   Hanasui            latte      3073
80                   Hanasui           matcha      3073
93                   Hanasui              non      3073
119                  Hanasui     transferable      3073
128                  Hanasui             with      3073
71                   Hanasui         lipcream      1044
15                   Hanasui              bdl       951
104                  Hanasui              sbd       733
43                   Hanasui            fancy       500
49                   Hanasui               fs       335
96                   Hanasui            ombre       329
110                  Hanasui          special       305
101                  Hanasui            promo       268
105                  Hanasui           series       268
0                    Hanasui               01       250
1                    Hanasui               04       250
2                    Hanasui               07       250
3                    Hanasui               08       250
4                    Hanasui               10       250
5                    Hanasui               11       250
6                    Hanasui               12       250
7                    Hanasui               14       250
8                    Hanasui               15       250
9                    Hanasui               16       250
10                   Hanasui                5       250
12                   Hanasui            amaze       250
25                   Hanasui            brick       250
28                   Hanasui             chic       250
29                   Hanasui           classy       250
38                   Hanasui            dusty       250
45                   Hanasui            flame       250
52                   Hanasui            glame       250
63                   Hanasui             kiss       250
109                  Hanasui           sparks       250
78                   Hanasui      longlasting        46
75                   Hanasui          liptint        38
46                   Hanasui            flash        26
58                   Hanasui              hot        26
103                  Hanasui             sale        26
26                   Hanasui         bundling        17
106                  Hanasui            serum        17
107                  Hanasui         sleeping        17
21                   Hanasui            blush         5
23                   Hanasui           bounce         5
24                   Hanasui           bouncy         5
64                   Hanasui              kit         5
36                   Hanasui              dct         0
48                   Hanasui             free         0
61                   Hanasui             icha         0
76                   Hanasui             live         0
79                   Hanasui             mask         0
87                   Hanasui          mineral         0
90                   Hanasui              mud         0
169        Implora Cosmetics              day    363480
190        Implora Cosmetics          implora    318430
214        Implora Cosmetics            matte    282441
207        Implora Cosmetics         lipstick    267825
150        Implora Cosmetics            bibir    262861
208        Implora Cosmetics          lipstik    253932
182        Implora Cosmetics            gloss    253295
234        Implora Cosmetics           ringan    185213
245        Implora Cosmetics               to    181740
210        Implora Cosmetics             lite    176159
144        Implora Cosmetics             acid    175649
188        Implora Cosmetics       hyaluronic    175649
205        Implora Cosmetics         lipcream    175649
216        Implora Cosmetics      melembapkan    175649
204        Implora Cosmetics              lip    109021
246        Implora Cosmetics    transferproof     99024
200        Implora Cosmetics          lasting     72072
211        Implora Cosmetics             long     72052
191        Implora Cosmetics          intense     64833
166        Implora Cosmetics            cream     45226
228        Implora Cosmetics        pigmented     34194
153        Implora Cosmetics        blurmatte     34191
158        Implora Cosmetics            caffe     34191
162        Implora Cosmetics        colorlock     34191
170        Implora Cosmetics           dengan     34191
232        Implora Cosmetics       protection     34191
240        Implora Cosmetics           shield     34191
249        Implora Cosmetics               uv     34191
235        Implora Cosmetics            satin     12481
250        Implora Cosmetics           velvet     11201
164        Implora Cosmetics         cosmetic     11135
248        Implora Cosmetics            urban     10672
244        Implora Cosmetics             tint      9973
220        Implora Cosmetics            ombre      7329
147        Implora Cosmetics         approved      7220
157        Implora Cosmetics               by      7219
201        Implora Cosmetics      latuconsina      7219
230        Implora Cosmetics           prilly      7219
209        Implora Cosmetics          liptint      6593
134        Implora Cosmetics                3      6404
165        Implora Cosmetics           crayon      6277
138        Implora Cosmetics                5      6224
176        Implora Cosmetics           finish      6204
184        Implora Cosmetics               gr      6204
192        Implora Cosmetics            jelly      5968
173        Implora Cosmetics                e      5941
221        Implora Cosmetics            omega      5941
252        Implora Cosmetics              vit      5941
253        Implora Cosmetics             with      5941
154        Implora Cosmetics           bullet      5066
179        Implora Cosmetics        gantungan      4959
198        Implora Cosmetics            kunci      4959
178        Implora Cosmetics             free      4924
194        Implora Cosmetics         keychain      4919
149        Implora Cosmetics             best      3453
163        Implora Cosmetics            combo      3453
212        Implora Cosmetics             look      3453
236        Implora Cosmetics          selling      3453
146        Implora Cosmetics              and      3381
159        Implora Cosmetics            cheek      3381
160        Implora Cosmetics           cherry      3357
168        Implora Cosmetics              dan      3357
199        Implora Cosmetics             lama      3357
227        Implora Cosmetics           perona      3357
229        Implora Cosmetics             pipi      3357
242        Implora Cosmetics            tahan      3357
238        Implora Cosmetics           series       729
171        Implora Cosmetics             dewy       624
129        Implora Cosmetics               01       340
130        Implora Cosmetics               03       340
224        Implora Cosmetics       passionate       340
247        Implora Cosmetics         uplifted       340
225        Implora Cosmetics              pcs       179
218        Implora Cosmetics            moist       155
155        Implora Cosmetics         bundling       154
239        Implora Cosmetics            serum       154
177        Implora Cosmetics              for       127
254        Implora Cosmetics                x       107
196        Implora Cosmetics           korean        70
206        Implora Cosmetics             lips        70
137        Implora Cosmetics              49k        53
167        Implora Cosmetics           creamy        46
186        Implora Cosmetics        hazelnude        39
187        Implora Cosmetics           honest        36
132        Implora Cosmetics                2        34
139        Implora Cosmetics              50k        27
223        Implora Cosmetics            paket        27
140        Implora Cosmetics              55k        24
143        Implora Cosmetics              70k        20
135        Implora Cosmetics                4        10
161        Implora Cosmetics             cici         7
175        Implora Cosmetics        exclusive         7
180        Implora Cosmetics            gemas         7
131        Implora Cosmetics                1         5
156        Implora Cosmetics              buy         5
181        Implora Cosmetics              get         5
237        Implora Cosmetics         serenity         5
136        Implora Cosmetics              45k         3
152        Implora Cosmetics         blooming         1
172        Implora Cosmetics              duo         1
183        Implora Cosmetics          glowing         1
193        Implora Cosmetics         kerajaan         1
133        Implora Cosmetics             2211         0
141        Implora Cosmetics             60ml         0
142        Implora Cosmetics              65k         0
145        Implora Cosmetics          aliyyah         0
148        Implora Cosmetics           barley         0
151        Implora Cosmetics            black         0
174        Implora Cosmetics         excluive         0
185        Implora Cosmetics            grape         0
189        Implora Cosmetics            iicha         0
195        Implora Cosmetics             kohl         0
197        Implora Cosmetics         kosmetik         0
202        Implora Cosmetics           launch         0
203        Implora Cosmetics            lemon         0
213        Implora Cosmetics           lotion         0
215        Implora Cosmetics            mawar         0
217        Implora Cosmetics            milky         0
219        Implora Cosmetics              new         0
222        Implora Cosmetics          package         0
226        Implora Cosmetics           pencil         0
231        Implora Cosmetics       priscillia         0
233        Implora Cosmetics           relaxa         0
241        Implora Cosmetics         softbrow         0
243        Implora Cosmetics           ticket         0
251        Implora Cosmetics           vilmei         0
289  L'Oreal Paris Indonesia                l     66477
311  L'Oreal Paris Indonesia            oreal     66477
314  L'Oreal Paris Indonesia            paris     66477
326  L'Oreal Paris Indonesia            tidak     64544
318  L'Oreal Paris Indonesia       resistance     63650
284  L'Oreal Paris Indonesia       infallible     63648
287  L'Oreal Paris Indonesia              jam     55669
256  L'Oreal Paris Indonesia               16     55181
328  L'Oreal Paris Indonesia    transferproof     55181
303  L'Oreal Paris Indonesia            matte     42826
297  L'Oreal Paris Indonesia         lipstick     40497
299  L'Oreal Paris Indonesia           liquid     40495
276  L'Oreal Paris Indonesia              for     34224
262  L'Oreal Paris Indonesia             acid     32502
283  L'Oreal Paris Indonesia       hyaluronic     32502
292  L'Oreal Paris Indonesia          lasting     32184
301  L'Oreal Paris Indonesia             long     32184
273  L'Oreal Paris Indonesia           dengan     32028
288  L'Oreal Paris Indonesia           kering     32028
327  L'Oreal Paris Indonesia         transfer     32028
298  L'Oreal Paris Indonesia          lipstik     25480
296  L'Oreal Paris Indonesia              lip     23651
282  L'Oreal Paris Indonesia           hingga     23641
271  L'Oreal Paris Indonesia            cream     23153
280  L'Oreal Paris Indonesia           glossy     23153
291  L'Oreal Paris Indonesia            laque     23153
302  L'Oreal Paris Indonesia      longlasting     23153
308  L'Oreal Paris Indonesia           nyaman     23153
315  L'Oreal Paris Indonesia        pigmented     23153
265  L'Oreal Paris Indonesia             baru     15183
300  L'Oreal Paris Indonesia       livestream      8466
324  L'Oreal Paris Indonesia          special      8447
270  L'Oreal Paris Indonesia            color      2329
286  L'Oreal Paris Indonesia          intense      2329
319  L'Oreal Paris Indonesia            riche      2329
330  L'Oreal Paris Indonesia           volume      2329
261  L'Oreal Paris Indonesia              611      2171
277  L'Oreal Paris Indonesia             free      2171
281  L'Oreal Paris Indonesia         hawthorn      2171
306  L'Oreal Paris Indonesia            naked      2171
307  L'Oreal Paris Indonesia              not      2171
321  L'Oreal Paris Indonesia             sale      2171
316  L'Oreal Paris Indonesia            plump       972
325  L'Oreal Paris Indonesia            tahan       644
267  L'Oreal Paris Indonesia            bibir       506
264  L'Oreal Paris Indonesia         ambition       498
310  L'Oreal Paris Indonesia              oil       498
258  L'Oreal Paris Indonesia               24       488
294  L'Oreal Paris Indonesia           lembab       488
295  L'Oreal Paris Indonesia          lengket       488
317  L'Oreal Paris Indonesia           plumpy       488
285  L'Oreal Paris Indonesia          instant       474
329  L'Oreal Paris Indonesia       tripeptide       474
290  L'Oreal Paris Indonesia             lama       156
266  L'Oreal Paris Indonesia             best        35
309  L'Oreal Paris Indonesia               of        35
313  L'Oreal Paris Indonesia             pack        35
274  L'Oreal Paris Indonesia        exclusive        25
255  L'Oreal Paris Indonesia              125        22
268  L'Oreal Paris Indonesia        cleansing        22
278  L'Oreal Paris Indonesia          garnier        22
304  L'Oreal Paris Indonesia         micellar        22
305  L'Oreal Paris Indonesia               ml        22
320  L'Oreal Paris Indonesia           sakura        22
331  L'Oreal Paris Indonesia            water        22
322  L'Oreal Paris Indonesia           seller        20
323  L'Oreal Paris Indonesia           shades        20
257  L'Oreal Paris Indonesia                2        18
279  L'Oreal Paris Indonesia            gloss        18
259  L'Oreal Paris Indonesia                3        15
269  L'Oreal Paris Indonesia            clear        11
272  L'Oreal Paris Indonesia          crystal        11
275  L'Oreal Paris Indonesia            flush         4
312  L'Oreal Paris Indonesia              out         4
260  L'Oreal Paris Indonesia                5         2
263  L'Oreal Paris Indonesia        affiliate         2
293  L'Oreal Paris Indonesia               le         2
398     Maybelline Indonesia            matte    372911
399     Maybelline Indonesia       maybelline    217250
444     Maybelline Indonesia        superstay    201985
387     Maybelline Indonesia         lipstick    201901
369     Maybelline Indonesia              ink    199185
445     Maybelline Indonesia            tahan    197396
390     Maybelline Indonesia           liquid    191178
377     Maybelline Indonesia          lasting    189895
392     Maybelline Indonesia             long    189895
394     Maybelline Indonesia             make    188492
455     Maybelline Indonesia               up    188492
371     Maybelline Indonesia              jam    182807
384     Maybelline Indonesia         lipcream    182448
333     Maybelline Indonesia               16    180059
459     Maybelline Indonesia       waterproof    179854
453     Maybelline Indonesia    transferproof    179853
452     Maybelline Indonesia           tinted     44382
343     Maybelline Indonesia             balm     29588
364     Maybelline Indonesia            glaze     29588
405     Maybelline Indonesia              new     23506
334     Maybelline Indonesia                2     19041
382     Maybelline Indonesia              lip     17773
365     Maybelline Indonesia            gloss     15310
380     Maybelline Indonesia           lifter     15052

In [30]:
position_rows = []

for brand, data in df.groupby("Brand"):
    for tokens in data["tokens"]:
        for i, word in enumerate(tokens):
            position_rows.append([brand, word, i+1])

pos_df = pd.DataFrame(position_rows, columns=["Brand", "Keyword", "Position"])

keyword_position = (
    pos_df.groupby(["Brand", "Keyword"])["Position"]
    .mean()
    .reset_index()
    .sort_values(["Brand", "Position"])
)

keyword_position

                       Brand          Keyword   Position
36                   Hanasui              dct   1.000000
42                   Hanasui        exclusive   1.000000
49                   Hanasui               fs   1.000000
58                   Hanasui              hot   1.000000
104                  Hanasui              sbd   1.000000
56                   Hanasui          hanasui   1.852941
35                   Hanasui          creator   2.000000
46                   Hanasui            flash   2.000000
76                   Hanasui             live   2.000000
101                  Hanasui            promo   2.000000
54                   Hanasui     glazedorable   2.500000
82                   Hanasui     mattedorable   2.866667
61                   Hanasui             icha   3.000000
103                  Hanasui             sale   3.000000
96                   Hanasui            ombre   3.333333
74                   Hanasui         lipstick   3.500000
116                  Hanasui      tintdorable   3.500000
125                  Hanasui            vinyl   3.500000
71                   Hanasui         lipcream   3.750000
105                  Hanasui           series   4.000000
110                  Hanasui          special   4.000000
92                   Hanasui             next   4.083333
13                   Hanasui             anti   4.500000
111                  Hanasui            stain   4.600000
68                   Hanasui            level   5.000000
51                   Hanasui            geser   5.500000
99                   Hanasui           plumpy   5.500000
22                   Hanasui             boba   5.800000
0                    Hanasui               01   6.000000
73                   Hanasui             lips   6.000000
121                  Hanasui         twinpack   6.250000
80                   Hanasui           matcha   6.333333
53                   Hanasui           glazed   6.500000
63                   Hanasui             kiss   7.000000
75                   Hanasui          liptint   7.000000
20                   Hanasui           blurry   7.200000
67                   Hanasui            latte   7.333333
34                   Hanasui            cream   7.416667
26                   Hanasui         bundling   7.500000
40                   Hanasui          edition   7.500000
64                   Hanasui              kit   7.500000
85                   Hanasui      melembapkan   7.500000
108                  Hanasui      smudgeproof   7.500000
70                   Hanasui              lip   7.892857
1                    Hanasui               04   8.000000
30                   Hanasui            color   8.000000
72                   Hanasui          liplast   8.083333
124                  Hanasui          vibrant   8.500000
120                  Hanasui    transferproof   8.750000
28                   Hanasui             chic   9.000000
127                  Hanasui           watery   9.000000
27                   Hanasui           butter   9.500000
31                   Hanasui           colour   9.500000
47                   Hanasui          formula   9.750000
10                   Hanasui                5  10.000000
107                  Hanasui         sleeping  10.000000
77                   Hanasui             long  10.200000
114                  Hanasui       technology  10.500000
89                   Hanasui    mouisturizing  10.666667
115                  Hanasui             tint  10.882353
18                   Hanasui             blur  11.000000
29                   Hanasui           classy  11.000000
106                  Hanasui            serum  11.000000
37                   Hanasui           double  11.166667
95                   Hanasui            olive  11.250000
59                   Hanasui        hydrating  11.500000
2                    Hanasui               07  12.000000
91                   Hanasui          natural  12.000000
123                  Hanasui           velvet  12.142857
113                  Hanasui            tahan  12.157895
66                   Hanasui          lasting  12.166667
94                   Hanasui              oil  12.250000
15                   Hanasui              bdl  12.428571
24                   Hanasui           bouncy  12.500000
128                  Hanasui             with  12.500000
81                   Hanasui            matte  12.642857
109                  Hanasui           sparks  13.000000
65                   Hanasui             lama  13.157895
88                   Hanasui     moisturizing  13.200000
126                  Hanasui          vitamin  13.333333
21                   Hanasui            blush  13.500000
16                   Hanasui           beauty  13.750000
102                  Hanasui           ringan  13.900000
3                    Hanasui               08  14.000000
48                   Hanasui             free  14.000000
69                   Hanasui      lightweight  14.000000
98                   Hanasui        pigmented  14.266667
39                   Hanasui                e  14.333333
83                   Hanasui          maximum  14.400000
57                   Hanasui          hidrasi  14.500000
84                   Hanasui      melembabkan  15.000000
86                   Hanasui      mencerahkan  15.000000
87                   Hanasui          mineral  15.000000
44                   Hanasui           finish  15.285714
33                   Hanasui         coverage  15.400000
122                  Hanasui               up  15.400000
97                   Hanasui          optimal  15.500000
17                   Hanasui            bibir  15.600000
4                    Hanasui               10  16.000000
43                   Hanasui            fancy  16.000000
90                   Hanasui              mud  16.000000
14                   Hanasui             balm  16.166667
118                  Hanasui               to  16.500000
79                   Hanasui             mask  17.000000
100                  Hanasui          powdery  17.000000
5                    Hanasui               11  18.000000
32                   Hanasui            cover  18.000000
93                   Hanasui              non  18.500000
117                  Hanasui           tinted  18.750000
19                   Hanasui         blurring  19.000000
25                   Hanasui            brick  19.000000
119                  Hanasui     transferable  19.500000
6                    Hanasui               12  20.000000
41                   Hanasui           effect  20.000000
50                   Hanasui            gelap  20.000000
55                   Hanasui            gloss  20.666667
78                   Hanasui      longlasting  20.666667
12                   Hanasui            amaze  21.000000
112                  Hanasui     stainlasting  21.000000
7                    Hanasui               14  22.000000
60                   Hanasui            hyper  22.000000
38                   Hanasui            dusty  23.000000
8                    Hanasui               15  24.000000
11                   Hanasui                8  24.000000
45                   Hanasui            flame  25.000000
62                   Hanasui              jam  25.000000
23                   Hanasui           bounce  25.500000
9                    Hanasui               16  26.000000
52                   Hanasui            glame  27.000000
136        Implora Cosmetics              45k   1.000000
137        Implora Cosmetics              49k   1.000000
140        Implora Cosmetics              55k   1.000000
142        Implora Cosmetics              65k   1.000000
143        Implora Cosmetics              70k   1.000000
149        Implora Cosmetics             best   1.000000
155        Implora Cosmetics         bundling   1.000000
156        Implora Cosmetics              buy   1.000000
174        Implora Cosmetics         excluive   1.000000
193        Implora Cosmetics         kerajaan   1.000000
222        Implora Cosmetics          package   1.000000
243        Implora Cosmetics           ticket   1.000000
145        Implora Cosmetics          aliyyah   2.000000
158        Implora Cosmetics            caffe   2.000000
164        Implora Cosmetics         cosmetic   2.000000
183        Implora Cosmetics          glowing   2.000000
189        Implora Cosmetics            iicha   2.000000
196        Implora Cosmetics           korean   2.000000
236        Implora Cosmetics          selling   2.000000
251        Implora Cosmetics           vilmei   2.000000
177        Implora Cosmetics              for   2.250000
139        Implora Cosmetics              50k   2.500000
190        Implora Cosmetics          implora   2.770833
135        Implora Cosmetics                4   3.000000
163        Implora Cosmetics            combo   3.000000
181        Implora Cosmetics              get   3.000000
191        Implora Cosmetics          intense   3.000000
195        Implora Cosmetics             kohl   3.000000
231        Implora Cosmetics       priscillia   3.000000
134        Implora Cosmetics                3   3.272727
138        Implora Cosmetics                5   3.833333
131        Implora Cosmetics                1   4.000000
159        Implora Cosmetics            cheek   4.000000
175        Implora Cosmetics        exclusive   4.000000
248        Implora Cosmetics            urban   4.000000
253        Implora Cosmetics             with   4.000000
254        Implora Cosmetics                x   4.000000
169        Implora Cosmetics              day   4.083333
245        Implora Cosmetics               to   4.083333
225        Implora Cosmetics              pcs   4.200000
171        Implora Cosmetics             dewy   4.500000
233        Implora Cosmetics           relaxa   4.555556
192        Implora Cosmetics            jelly   4.666667
146        Implora Cosmetics              and   5.000000
165        Implora Cosmetics           crayon   5.000000
206        Implora Cosmetics             lips   5.000000
221        Implora Cosmetics            omega   5.000000
132        Implora Cosmetics                2   5.500000
147        Implora Cosmetics         approved   5.500000
205        Implora Cosmetics         lipcream   5.600000
218        Implora Cosmetics            moist   5.750000
148        Implora Cosmetics           barley   6.000000
186        Implora Cosmetics        hazelnude   6.000000
219        Implora Cosmetics              new   6.000000
227        Implora Cosmetics           perona   6.000000
238        Implora Cosmetics           series   6.000000
252        Implora Cosmetics              vit   6.000000
250        Implora Cosmetics           velvet   6.111111
214        Implora Cosmetics            matte   6.150000
204        Implora Cosmetics              lip   6.177778
244        Implora Cosmetics             tint   6.500000
246        Implora Cosmetics    transferproof   6.500000
152        Implora Cosmetics         blooming   6.666667
173        Implora Cosmetics                e   7.000000
185        Implora Cosmetics            grape   7.000000
187        Implora Cosmetics           honest   7.000000
197        Implora Cosmetics         kosmetik   7.000000
202        Implora Cosmetics           launch   7.000000
210        Implora Cosmetics             lite   7.000000
223        Implora Cosmetics            paket   7.000000
239        Implora Cosmetics            serum   7.000000
194        Implora Cosmetics         keychain   7.500000
172        Implora Cosmetics              duo   7.666667
209        Implora Cosmetics          liptint   7.833333
166        Implora Cosmetics            cream   7.875000
220        Implora Cosmetics            ombre   7.900000
129        Implora Cosmetics               01   8.000000
154        Implora Cosmetics           bullet   8.000000
168        Implora Cosmetics              dan   8.000000
170        Implora Cosmetics           dengan   8.000000
203        Implora Cosmetics            lemon   8.000000
241        Implora Cosmetics         softbrow   8.000000
235        Implora Cosmetics            satin   8.166667
184        Implora Cosmetics               gr   8.500000
208        Implora Cosmetics          lipstik   8.833333
157        Implora Cosmetics               by   9.000000
212        Implora Cosmetics             look   9.000000
216        Implora Cosmetics      melembapkan   9.000000
226        Implora Cosmetics           pencil   9.000000
229        Implora Cosmetics             pipi   9.000000
247        Implora Cosmetics         uplifted   9.000000
249        Implora Cosmetics               uv   9.000000
207        Implora Cosmetics         lipstick   9.400000
161        Implora Cosmetics             cici   9.500000
211        Implora Cosmetics             long   9.500000
150        Implora Cosmetics            bibir   9.545455
130        Implora Cosmetics               03  10.000000
151        Implora Cosmetics            black  10.000000
167        Implora Cosmetics           creamy  10.000000
178        Implora Cosmetics             free  10.000000
179        Implora Cosmetics        gantungan  10.000000
188        Implora Cosmetics       hyaluronic  10.000000
230        Implora Cosmetics           prilly  10.000000
234        Implora Cosmetics           ringan  10.000000
237        Implora Cosmetics         serenity  10.000000
240        Implora Cosmetics           shield  10.000000
242        Implora Cosmetics            tahan  10.000000
182        Implora Cosmetics            gloss  10.090909
200        Implora Cosmetics          lasting  10.333333
180        Implora Cosmetics            gemas  10.500000
144        Implora Cosmetics             acid  11.000000
160        Implora Cosmetics           cherry  11.000000
198        Implora Cosmetics            kunci  11.000000
199        Implora Cosmetics             lama  11.000000
201        Implora Cosmetics      latuconsina  11.000000
224        Implora Cosmetics       passionate  11.000000
228        Implora Cosmetics        pigmented  11.000000
232        Implora Cosmetics       protection  11.000000
215        Implora Cosmetics            mawar  12.000000
162        Implora Cosmetics        colorlock  13.000000
217        Implora Cosmetics            milky  13.000000
176        Implora Cosmetics           finish  13.500000
153        Implora Cosmetics        blurmatte  14.000000
213        Implora Cosmetics           lotion  14.000000
133        Implora Cosmetics             2211  15.000000
141        Implora Cosmetics             60ml  15.000000
265  L'Oreal Paris Indonesia             baru   1.000000
266  L'Oreal Paris Indonesia             best   1.000000
274  L'Oreal Paris Indonesia        exclusive   1.000000
307  L'Oreal Paris Indonesia              not   1.000000
324  L'Oreal Paris Indonesia          special   1.000000
263  L'Oreal Paris Indonesia        affiliate   2.000000
275  L'Oreal Paris Indonesia            flush   2.000000
322  L'Oreal Paris Indonesia           seller   2.000000
300  L'Oreal Paris Indonesia       livestream   2.750000
312  L'Oreal Paris Indonesia              out   3.000000
321  L'Oreal Paris Indonesia             sale   3.000000
323  L'Oreal Paris Indonesia           shades   3.000000
313  L'Oreal Paris Indonesia             pack   3.333333
259  L'Oreal Paris Indonesia                3   4.000000
293  L'Oreal Paris Indonesia               le   4.000000
309  L'Oreal Paris Indonesia               of   4.333333
289  L'Oreal Paris Indonesia                l   4.461538
311  L'Oreal Paris Indonesia            oreal   5.461538
257  L'Oreal Paris Indonesia                2   6.000000
260  L'Oreal Paris Indonesia                5   6.000000
264  L'Oreal Paris Indonesia         ambition   6.142857
316  L'Oreal Paris Indonesia            plump   6.444444
314  L'Oreal Paris Indonesia            paris   6.461538
277  L'Oreal Paris Indonesia             free   7.000000
291  L'Oreal Paris Indonesia            laque   7.000000
270  L'Oreal Paris Indonesia            color   7.500000
276  L'Oreal Paris Indonesia              for   8.000000
310  L'Oreal Paris Indonesia              oil   8.142857
278  L'Oreal Paris Indonesia          garnier   8.500000
296  L'Oreal Paris Indonesia              lip   8.500000
319  L'Oreal Paris Indonesia            riche   8.500000
284  L'Oreal Paris Indonesia       infallible   8.928571
272  L'Oreal Paris Indonesia          crystal   9.000000
286  L'Oreal Paris Indonesia          intense   9.500000
304  L'Oreal Paris Indonesia         micellar   9.500000
269  L'Oreal Paris Indonesia            clear  10.000000
285  L'Oreal Paris Indonesia          instant  10.000000
268  L'Oreal Paris Indonesia        cleansing  10.500000
330  L'Oreal Paris Indonesia           volume  10.500000
303  L'Oreal Paris Indonesia            matte  10.562500
318  L'Oreal Paris Indonesia       resistance  10.600000
331  L'Oreal Paris Indonesia            water  11.500000
290  L'Oreal Paris Indonesia             lama  12.500000
320  L'Oreal Paris Indonesia           sakura  12.500000
271  L'Oreal Paris Indonesia            cream  12.666667
299  L'Oreal Paris Indonesia           liquid  12.727273
297  L'Oreal Paris Indonesia         lipstick  13.166667
255  L'Oreal Paris Indonesia              125  13.500000
280  L'Oreal Paris Indonesia           glossy  13.666667
261  L'Oreal Paris Indonesia              611  14.000000
298  L'Oreal Paris Indonesia          lipstik  14.000000
329  L'Oreal Paris Indonesia       tripeptide  14.000000
305  L'Oreal Paris Indonesia               ml  14.500000
315  L'Oreal Paris Indonesia        pigmented  14.666667
306  L'Oreal Paris Indonesia            naked  15.000000
301  L'Oreal Paris Indonesia             long  15.142857
325  L'Oreal Paris Indonesia            tahan  15.625000
308  L'Oreal Paris Indonesia           nyaman  15.666667
281  L'Oreal Paris Indonesia         hawthorn  16.000000
292  L'Oreal Paris Indonesia          lasting  16.142857
256  L'Oreal Paris Indonesia               16  16.375000
287  L'Oreal Paris Indonesia              jam  18.500000
282  L'Oreal Paris Indonesia           hingga  18.555556
302  L'Oreal Paris Indonesia      longlasting  18.666667
327  L'Oreal Paris Indonesia         transfer  18.800000
258  L'Oreal Paris Indonesia               24  19.000000
328  L'Oreal Paris Indonesia    transferproof  19.000000
283  L'Oreal Paris Indonesia       hyaluronic  20.428571
326  L'Oreal Paris Indonesia            tidak  21.062500
262  L'Oreal Paris Indonesia             acid  21.428571
288  L'Oreal Paris Indonesia           kering  21.800000
317  L'Oreal Paris Indonesia           plumpy  22.000000
267  L'Oreal Paris Indonesia            bibir  22.142857
273  L'Oreal Paris Indonesia           dengan  22.800000
294  L'Oreal Paris Indonesia           lembab  23.000000
295  L'Oreal Paris Indonesia          lengket  25.000000
279  L'Oreal Paris Indonesia            gloss  28.000000
356     Maybelline Indonesia        exclusive   1.000000
366     Maybelline Indonesia            hanya   1.000000
372     Maybelline Indonesia            jordi   1.000000
405     Maybelline Indonesia              new   1.000000
425     Maybelline Indonesia           rp39rb   1.000000
440     Maybelline Indonesia          special   1.000000
448     Maybelline Indonesia            tebus   1.000000
458     Maybelline Indonesia           vonvon   1.000000
391     Maybelline Indonesia             live   1.666667
349     Maybelline Indonesia            color   2.000000
352     Maybelline Indonesia          creator   2.000000
363     Maybelline Indonesia               fs   2.000000
378     Maybelline Indonesia           launch   2.000000
403     Maybelline Indonesia            murah   2.000000
406     Maybelline Indonesia           nikmir   2.000000
411     Maybelline Indonesia             onsu   2.000000
413     Maybelline Indonesia               pc   2.000000

In [31]:
top_global_keywords = (
    keyword_revenue.groupby("Keyword")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

top_global_keywords

Keyword
matte            3.903203e+10
lip              3.129753e+10
lipstick         2.488522e+10
tahan            2.106901e+10
lasting          1.836012e+10
long             1.771468e+10
jam              1.754638e+10
transferproof    1.705666e+10
up               1.589730e+10
make             1.540746e+10
16               1.432725e+10
liquid           1.423296e+10
cream            1.343832e+10
lipcream         1.341699e+10
maybelline       1.321503e+10
balm             1.272848e+10
superstay        1.268139e+10
ink              1.233267e+10
waterproof       1.119109e+10
tint             1.043073e+10
Name: Revenue, dtype: float64

In [32]:
top_words = top_global_keywords.index.tolist()[:5]

" ".join(top_words)

'matte lip lipstick tahan lasting'

In [33]:
# gabungkan ranking
merge_rank = keyword_revenue.merge(
    keyword_sold, on=["Brand", "Keyword"], how="left"
)

merge_rank["score"] = merge_rank["Revenue"] + merge_rank["ItemSold"]

best_keywords = (
    merge_rank.groupby("Keyword")["score"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

best_keywords

Keyword
matte            3.903296e+10
lip              3.129828e+10
lipstick         2.488583e+10
tahan            2.106952e+10
lasting          1.836051e+10
long             1.771505e+10
jam              1.754670e+10
transferproof    1.705705e+10
up               1.589759e+10
make             1.540770e+10
Name: score, dtype: float64

In [34]:
import random

best_list = best_keywords.index.tolist()

recommendations = []

for _ in range(10):
    sample = random.sample(best_list, min(5, len(best_list)))
    recommendations.append(" ".join(sample))

recommendations

['up lipstick long jam make',
 'lipstick tahan jam transferproof matte',
 'transferproof lip lipstick up matte',
 'up lip long lasting make',
 'lipstick make lasting up matte',
 'long make matte jam lasting',
 'transferproof lasting tahan matte lipstick',
 'jam matte make tahan transferproof',
 'jam long matte tahan lip',
 'lipstick transferproof tahan up long']

In [35]:
top_brand = (
    df.groupby("Brand")["Revenue(Rp)"]
    .sum()
    .sort_values(ascending=False)
    .index[0]
)

top_brand

'Maybelline Indonesia'

In [36]:
brand_template_words = (
    keyword_revenue[keyword_revenue["Brand"] == top_brand]
    .sort_values("Revenue", ascending=False)
    .head(10)["Keyword"]
    .tolist()
)

brand_template_words

['matte',
 'maybelline',
 'superstay',
 'lipstick',
 'ink',
 'lasting',
 'long',
 'liquid',
 'tahan',
 'make']

In [37]:
" ".join(brand_template_words[:5])

'matte maybelline superstay lipstick ink'

Dari pengamatan pola marketplace & data kamu biasanya formatnya Pola umum yang PALING sering muncul :

**[Brand / Series] + [Tipe Produk] + [Hero Ingredient / Varian] + [Benefit Utama] + [Benefit Tambahan] + [Trust / Legal / Target]**

---

Kalau disederhanakan → jadi 3 blok besar

Brand / Identity :

- Hanasui
- Implora Cosmetics
- Maybelline Indonesia
- Timephoria Id
- L'Oreal Paris Indonesia


Kadang ditambah:
- series
- line
- level

contoh:
**Hanasui Next Level, Azarine Hydrasoothe, dll.**

---

**Jenis Produk (WHAT IS IT)**

Biasanya kata yang langsung dicari orang.

Contoh:
- serum
- sunscreen
- lip cream
- toner
- moisturizer
- cushion

ini magnet search.

---

**Keunggulan (WHY BUY)**

Biasanya terdiri dari beberapa layer:

1. Benefit fungsi
    - brightening
    - acne care
    - calming
    - anti aging

2. Hasil Akhir
    - matte
    - glowing
    - atural
    - performa
    - tahan lama
    - waterproof
    - cepat meresap
    - kandungan
    - niacinamide
    - salicylic acid
    - trust
    - bpom
    - halal

---

Brand besar jarang membuat judul pendek.

Mereka :
- mengulang tipe produk
- menumpuk benefit
- memasukkan kata yang sering dicari
- membuat judul panjang untuk SEO

---

Template Paling Umum di Dataset Kompetitor

**Brand + Series + Jenis Produk - Jenis Produk + Benefit 1 + Benefit 2 + Benefit 3 + Extra**

Perhatikan :
**setelah tanda "-" sering diulang lagi jenis produknya.**

---

Contoh nyata kalau kita pakai rumus itu

Misal : Azarine Sunscreen

Maka menjadi:
**Azarine Hydrasoothe Sunscreen SPF45 - Sunscreen Wajah Melembabkan Tanpa Whitecast Ringan BPOM**

Kenapa ini efektif?

Karena mengandung :

- identitas brand
- produk yang dicari
- solusi masalah
- kelebihan dibanding kompetitor
- keyword SEO

## **Kesimpulan pola dari dataset**

**- IDENTITAS → PRODUK → PENARIK PERHATIAN → PENGUAT KEYWORD**

**- Brand → Product Type → Benefit → Performance → Trust**

In [38]:
import pandas as pd
import re
from collections import Counter


# =============================
# TEXT CLEANING
# =============================
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df["clean_name"] = df["Product Name"].apply(clean_text)

# =============================
# TOKENIZE
# =============================
df["tokens"] = df["clean_name"].str.split()

# =============================
# HITUNG FREKUENSI PER BRAND
# =============================
results = []

for brand in df["Brand"].dropna().unique():
    
    brand_df = df[df["Brand"] == brand]
    
    all_words = []
    for words in brand_df["tokens"]:
        all_words.extend(words)
    
    counter = Counter(all_words)
    
    temp = pd.DataFrame(counter.items(), columns=["keyword", "frequency"])
    temp["brand"] = brand
    
    # urutkan dari paling sering
    temp = temp.sort_values(by="frequency", ascending=False)
    
    results.append(temp)

# =============================
# GABUNGKAN HASIL
# =============================
final_keyword_frequency = pd.concat(results).reset_index(drop=True)

# =============================
# TAMPILKAN SEMUA
# =============================
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

final_keyword_frequency

# tampilkan
final_keyword_frequency

             keyword  frequency                    brand
0         maybelline         39     Maybelline Indonesia
1          superstay         32     Maybelline Indonesia
2           lipstick         26     Maybelline Indonesia
3                ink         25     Maybelline Indonesia
4              matte         22     Maybelline Indonesia
5              vinyl         16     Maybelline Indonesia
6            lipstik         16     Maybelline Indonesia
7                  2         16     Maybelline Indonesia
8             liquid         14     Maybelline Indonesia
9                jam         12     Maybelline Indonesia
10             teddy         12     Maybelline Indonesia
11          lipcream         12     Maybelline Indonesia
12             ombre         12     Maybelline Indonesia
13                ml         11     Maybelline Indonesia
14                up         11     Maybelline Indonesia
15              make         11     Maybelline Indonesia
16               set         11     Maybelline Indonesia
17              free         10     Maybelline Indonesia
18              tint         10     Maybelline Indonesia
19             tahan         10     Maybelline Indonesia
20               pcs          9     Maybelline Indonesia
21               lip          9     Maybelline Indonesia
22           lasting          8     Maybelline Indonesia
23              long          8     Maybelline Indonesia
24             shiny          8     Maybelline Indonesia
25         pigmented          7     Maybelline Indonesia
26                12          7     Maybelline Indonesia
27             gloss          7     Maybelline Indonesia
28                 5          6     Maybelline Indonesia
29        waterproof          6     Maybelline Indonesia
30          lipombre          5     Maybelline Indonesia
31             hemat          5     Maybelline Indonesia
32                 4          5     Maybelline Indonesia
33              soft          5     Maybelline Indonesia
34       longlasting          5     Maybelline Indonesia
35                16          5     Maybelline Indonesia
36             kulit          5     Maybelline Indonesia
37             paket          5     Maybelline Indonesia
38           special          4     Maybelline Indonesia
39           remover          4     Maybelline Indonesia
40                 x          4     Maybelline Indonesia
41            lifter          4     Maybelline Indonesia
42     transferproof          4     Maybelline Indonesia
43           edition          4     Maybelline Indonesia
44             cerah          4     Maybelline Indonesia
45              live          3     Maybelline Indonesia
46         exclusive          3     Maybelline Indonesia
47           creator          3     Maybelline Indonesia
48            makeup          3     Maybelline Indonesia
49             plump          3     Maybelline Indonesia
50       sensational          3     Maybelline Indonesia
51               new          3     Maybelline Indonesia
52            sachet          3     Maybelline Indonesia
53           limited          3     Maybelline Indonesia
54           liptint          3     Maybelline Indonesia
55            tinted          3     Maybelline Indonesia
56              onsu          2     Maybelline Indonesia
57             tebus          2     Maybelline Indonesia
58             color          2     Maybelline Indonesia
59              acid          2     Maybelline Indonesia
60        hyaluronic          2     Maybelline Indonesia
61            dengan          2     Maybelline Indonesia
62              ssvi          2     Maybelline Indonesia
63              ssmi          2     Maybelline Indonesia
64               for          2     Maybelline Indonesia
65             glaze          2     Maybelline Indonesia
66              balm          2     Maybelline Indonesia
67               oil          2     Maybelline Indonesia
68             jordi          2     Maybelline Indonesia
69             hanya          2     Maybelline Indonesia
70          fearless          2     Maybelline Indonesia
71             inspo          2     Maybelline Indonesia
72           perfect          2     Maybelline Indonesia
73             pouch          2     Maybelline Indonesia
74              lama          2     Maybelline Indonesia
75             murah          2     Maybelline Indonesia
76            vonvon          1     Maybelline Indonesia
77               tas          1     Maybelline Indonesia
78             serut          1     Maybelline Indonesia
79              rsbd          1     Maybelline Indonesia
80              puff          1     Maybelline Indonesia
81             korea          1     Maybelline Indonesia
82             viral          1     Maybelline Indonesia
83                x2          1     Maybelline Indonesia
84            curler          1     Maybelline Indonesia
85               bag          1     Maybelline Indonesia
86            silver          1     Maybelline Indonesia
87            bundle          1     Maybelline Indonesia
88          birthday          1     Maybelline Indonesia
89                pc          1     Maybelline Indonesia
90            rp39rb          1     Maybelline Indonesia
91                 3          1     Maybelline Indonesia
92              3pcs          1     Maybelline Indonesia
93               kit          1     Maybelline Indonesia
94                fs          1     Maybelline Indonesia
95            nikmir          1     Maybelline Indonesia
96             sauce          1     Maybelline Indonesia
97             rouge          1     Maybelline Indonesia
98             lippy          1     Maybelline Indonesia
99        captivated          1     Maybelline Indonesia
100            fresh          1     Maybelline Indonesia
101         poreless          1     Maybelline Indonesia
102           matang          1     Maybelline Indonesia
103             sawo          1     Maybelline Indonesia
104           shades          1     Maybelline Indonesia
105             milk          1     Maybelline Indonesia
106              tea          1     Maybelline Indonesia
107           launch          1     Maybelline Indonesia
108         official          1     Maybelline Indonesia
109          lipbalm          1     Maybelline Indonesia
110            tidak          1     Maybelline Indonesia
111          lengket          1     Maybelline Indonesia
112          natural          1     Maybelline Indonesia
113           ringan          1     Maybelline Indonesia
114              non          1     Maybelline Indonesia
115           sticky          1     Maybelline Indonesia
116            bibir          1     Maybelline Indonesia
117              fit          1     Maybelline Indonesia
118               me          1     Maybelline Indonesia
119          control          1     Maybelline Indonesia
120          compact          1     Maybelline Indonesia
121           powder          1     Maybelline Indonesia
122            shade          1     Maybelline Indonesia
123        ultimatte          1     Maybelline Indonesia
124             slim          1     Maybelline Indonesia
125               3d          1     Maybelline Indonesia
126              sbd          1     Maybelline Indonesia
127          mascara          1     Maybelline Indonesia
128               2x          1     Maybelline Indonesia
129       foundation          1     Maybelline Indonesia
130                l         26  L'Oreal Paris Indonesia
131            paris         26  L'Oreal Paris Indonesia
132            oreal         26  L'Oreal Paris Indonesia
133            matte         16  L'Oreal Paris Indonesia
134            tidak         16  L'Oreal Paris Indonesia
135       resistance         15  L'Oreal Paris Indonesia
136       infallible         14  L'Oreal Paris Indonesia
137              jam         14  L'Oreal Paris Indonesia
138         lipstick         12  L'Oreal Paris Indonesia
139           liquid         11  L'Oreal Paris Indonesia
140              lip         10  L'Oreal Paris Indonesia
141           hingga          9  L'Oreal Paris Indonesia
142            plump          9  L'Oreal Paris Indonesia
143              for          9  L'Oreal Paris Indonesia
144    transferproof          8  L'Oreal Paris Indonesia
145               16          8  L'Oreal Paris Indonesia
146            tahan          8  L'Oreal Paris Indonesia
147          lasting          7  L'Oreal Paris Indonesia
148             long          7  L'Oreal Paris Indonesia
149       hyaluronic          7  L'Oreal Paris Indonesia
150             acid          7  L'Oreal Paris Indonesia
151            bibir          7  L'Oreal Paris Indonesia
152              oil          7  L'Oreal Paris Indonesia
153         ambition          7  L'Oreal Paris Indonesia
154          lengket          6  L'Oreal Paris Indonesia
155           plumpy          6  L'Oreal Paris Indonesia
156           lembab          6  L'Oreal Paris Indonesia
157               24          6  L'Oreal Paris Indonesia
158          lipstik          6  L'Oreal Paris Indonesia
159         transfer          5  L'Oreal Paris Indonesia
160           kering          5  L'Oreal Paris Indonesia
161           dengan          5  L'Oreal Paris Indonesia
162          special          4  L'Oreal Paris Indonesia
163       livestream          4  L'Oreal Paris Indonesia
164           volume          4  L'Oreal Paris Indonesia
165          intense          4  L'Oreal Paris Indonesia
166            riche          4  L'Oreal Paris Indonesia
167            color          4  L'Oreal Paris Indonesia
168               of          3  L'Oreal Paris Indonesia
169             pack          3  L'Oreal Paris Indonesia
170             best          3  L'Oreal Paris Indonesia
171      longlasting          3  L'Oreal Paris Indonesia
172            laque          3  L'Oreal Paris Indonesia
173            cream          3  L'Oreal Paris Indonesia
174           glossy          3  L'Oreal Paris Indonesia
175        pigmented          3  L'Oreal Paris Indonesia
176           nyaman          3  L'Oreal Paris Indonesia
177        exclusive          3  L'Oreal Paris Indonesia
178            clear          2  L'Oreal Paris Indonesia
179              125          2  L'Oreal Paris Indonesia
180               ml          2  L'Oreal Paris Indonesia
181           sakura          2  L'Oreal Paris Indonesia
182        affiliate          2  L'Oreal Paris Indonesia
183            water          2  L'Oreal Paris Indonesia
184        cleansing          2  L'Oreal Paris Indonesia
185         micellar          2  L'Oreal Paris Indonesia
186          garnier          2  L'Oreal Paris Indonesia
187           seller          2  L'Oreal Paris Indonesia
188          crystal          2  L'Oreal Paris Indonesia
189          instant          2  L'Oreal Paris Indonesia
190           shades          2  L'Oreal Paris Indonesia
191             lama          2  L'Oreal Paris Indonesia
192             baru          2  L'Oreal Paris Indonesia
193       tripeptide          2  L'Oreal Paris Indonesia
194            naked          1  L'Oreal Paris Indonesia
195              611          1  L'Oreal Paris Indonesia
196             free          1  L'Oreal Paris Indonesia
197             sale          1  L'Oreal Paris Indonesia
198              not          1  L'Oreal Paris Indonesia
199            flush          1  L'Oreal Paris Indonesia
200               le          1  L'Oreal Paris Indonesia
201              out          1  L'Oreal Paris Indonesia
202            gloss          1  L'Oreal Paris Indonesia
203                5          1  L'Oreal Paris Indonesia
204                3          1  L'Oreal Paris Indonesia
205                2          1  L'Oreal Paris Indonesia
206         hawthorn          1  L'Oreal Paris Indonesia
207          implora         48        Implora Cosmetics
208              lip         45        Implora Cosmetics
209              day         24        Implora Cosmetics
210            matte         20        Implora Cosmetics
211            cream         16        Implora Cosmetics
212         lipstick         15        Implora Cosmetics
213              for         12        Implora Cosmetics
214               to         12        Implora Cosmetics
215                x         11        Implora Cosmetics
216            bibir         11        Implora Cosmetics
217            gloss         11        Implora Cosmetics
218                3         11        Implora Cosmetics
219            ombre         10        Implora Cosmetics
220             tint         10        Implora Cosmetics
221              pcs         10        Implora Cosmetics
222           velvet          9        Implora Cosmetics
223           relaxa          9        Implora Cosmetics
224                5          6        Implora Cosmetics
225            jelly          6        Implora Cosmetics
226          liptint          6        Implora Cosmetics
227             free          6        Implora Cosmetics
228            satin          6        Implora Cosmetics
229          lipstik          6        Implora Cosmetics
230             lite          6        Implora Cosmetics
231           bullet          5        Implora Cosmetics
232                4          5        Implora Cosmetics
233        exclusive          5        Implora Cosmetics
234           ringan          5        Implora Cosmetics
235         lipcream          5        Implora Cosmetics
236           crayon          4        Implora Cosmetics
237            moist          4        Implora Cosmetics
238         bundling          4        Implora Cosmetics
239                2          4        Implora Cosmetics
240            urban          4        Implora Cosmetics
241              duo          3        Implora Cosmetics
242       priscillia          3        Implora Cosmetics
243              get          3        Implora Cosmetics
244                1          3        Implora Cosmetics
245              45k          3        Implora Cosmetics
246          lasting          3        Implora Cosmetics
247              buy          3        Implora Cosmetics
248         blooming          3        Implora Cosmetics
249              49k          3        Implora Cosmetics
250            iicha          3        Implora Cosmetics
251           series          3        Implora Cosmetics
252           korean          2        Implora Cosmetics
253           launch          2        Implora Cosmetics
254           honest          2        Implora Cosmetics
255         approved          2        Implora Cosmetics
256             long          2        Implora Cosmetics
257           cherry          2        Implora Cosmetics
258    transferproof          2        Implora Cosmetics
259               gr          2        Implora Cosmetics
260           finish          2        Implora Cosmetics
261              new          2        Implora Cosmetics
262              and          2        Implora Cosmetics
263        pigmented          2        Implora Cosmetics
264            cheek          2        Implora Cosmetics
265            gemas          2        Implora Cosmetics
266             lips          2        Implora Cosmetics
267             dewy          2        Implora Cosmetics
268        gantungan          2        Implora Cosmetics
269              70k          2        Implora Cosmetics
270         keychain          2        Implora Cosmetics
271              50k          2        Implora Cosmetics
272             cici          2        Implora Cosmetics
273            kunci          2        Implora Cosmetics
274           vilmei          1        Implora Cosmetics
275           ticket          1        Implora Cosmetics
276          package          1        Implora Cosmetics
277           barley          1        Implora Cosmetics
278           lotion          1        Implora Cosmetics
279         serenity          1        Implora Cosmetics
280         kerajaan          1        Implora Cosmetics
281          glowing          1        Implora Cosmetics
282            milky          1        Implora Cosmetics
283             kohl          1        Implora Cosmetics
284          aliyyah          1        Implora Cosmetics
285            lemon          1        Implora Cosmetics
286         excluive          1        Implora Cosmetics
287            mawar          1        Implora Cosmetics
288             2211          1        Implora Cosmetics
289              65k          1        Implora Cosmetics
290         softbrow          1        Implora Cosmetics
291            black          1        Implora Cosmetics
292         kosmetik          1        Implora Cosmetics
293             60ml          1        Implora Cosmetics
294           pencil          1        Implora Cosmetics
295            tahan          1        Implora Cosmetics
296            paket          1        Implora Cosmetics
297            omega          1        Implora Cosmetics
298      latuconsina          1        Implora Cosmetics
299           prilly          1        Implora Cosmetics
300               by          1        Implora Cosmetics
301         cosmetic          1        Implora Cosmetics
302        blurmatte          1        Implora Cosmetics
303        colorlock          1        Implora Cosmetics
304       protection          1        Implora Cosmetics
305           shield          1        Implora Cosmetics
306               uv          1        Implora Cosmetics
307           dengan          1        Implora Cosmetics
308            caffe          1        Implora Cosmetics
309          intense          1        Implora Cosmetics
310             acid          1        Implora Cosmetics
311       hyaluronic          1        Implora Cosmetics
312      melembapkan          1        Implora Cosmetics
313             with          1        Implora Cosmetics
314              vit          1        Implora Cosmetics
315        hazelnude          1        Implora Cosmetics
316                e          1        Implora Cosmetics
317              55k          1        Implora Cosmetics
318           creamy          1        Implora Cosmetics
319            serum          1        Implora Cosmetics
320       passionate          1        Implora Cosmetics
321               03          1        Implora Cosmetics
322         uplifted          1        Implora Cosmetics
323               01          1        Implora Cosmetics
324             lama          1        Implora Cosmetics
325             pipi          1        Implora Cosmetics
326              dan          1        Implora Cosmetics
327           perona          1        Implora Cosmetics
328             look          1        Implora Cosmetics
329            combo          1        Implora Cosmetics
330          selling          1        Implora Cosmetics
331             best          1        Implora Cosmetics
332            grape          1        Implora Cosmetics
333              lip        118            Timephoria Id
334         lipstick         35            Timephoria Id
335           phoria         34            Timephoria Id
336             time         34            Timephoria Id
337       timephoria         32            Timephoria Id
338            matte         31            Timephoria Id
339            cream         26            Timephoria Id
340            stain         25            Timephoria Id
341             make         23            Timephoria Id
342             2pcs         23            Timephoria Id
343            gloss         22            Timephoria Id
344              5ml         22            Timephoria Id
345             tint         22            Timephoria Id
346          stellar         22            Timephoria Id
347             dust         22            Timephoria Id
348           velvet         19            Timephoria Id